theme: jekyll-theme-minimal
title: Yunas Qazi
description: Software Engineer turned Engineering Manager and still learning
logo: https://avatars2.githubusercontent.com/u/213712?s=400&v=4
google_analytics: UA-146643924-4